services:
  fixithub-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: fixithub
    volumes:
      - fixithub-volume:/app
  nginx:
    image: nginx:alpine
    container_name: fixithub-nginx
    restart: unless-stopped
    ports:
      - 4444:80
    volumes:
      - fixithub-volume:/var/www/html
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - fixithub-web
volumes:
  fixithub-volume:
    driver: local
